version: '3.3'
services:
  boerse:
    environment:
      - PYTHONUNBUFFERED=1
      - HOST=127.0.0.1
      - PORT=12345
    ports:
      - 12345:12345/udp
    build: ./
  bank:
    environment:
      - PYTHONUNBUFFERED=1
      - HOST=127.0.0.1
      - PORT=12345
    network_mode: "host"
    depends_on:
      - boerse
    build: ../bank/